#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setup virtualenvwrapper
source /usr/bin/virtualenvwrapper.sh

# Setup GOPATH
export GOPATH=$HOME/dev/go
export PATH=$PATH:$GOPATH/bin

# Setup Nodejs binary path
export PATH="$PATH:$HOME/.npm/bin"
